name: take_web
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core:
  firebase_analytics:
  firebase_auth:
  cloud_firestore:
  google_maps_flutter_web: ^0.4.0+3
  change_app_package_name: ^0.1.3
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  filter_list: ^1.0.2
  full_screen_image_null_safe: ^2.0.0
  csc_picker: ^0.2.6
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  flutter_styled_toast: ^2.1.3
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  firebase_storage:
  font_awesome_flutter: ^10.2.1
  internet_connection_checker: ^1.0.0+1
  google_maps_flutter: ^2.2.2
  flutter_image_compress: ^1.1.3
  file_picker: ^5.2.4
  archive: ^3.3.5
  image_picker_web: ^3.0.0+1
  url_launcher: ^6.1.7
  flutter_html: ^2.2.1
  georange: ^1.0.0
  flutter_local_notifications: ^9.1.4
  firebase_messaging: ^14.2.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  flutter_riverpod: ^2.1.3
  shimmer: ^2.0.0
  spell_checker: ^0.1.2+3
  flutter_polyline_points: ^1.0.0
  g_recaptcha_v3: ^0.0.5
  go_router: ^6.2.0
  flutter_share: ^2.0.0
  cached_network_image: ^3.2.3
  built_value: ^8.4.4
  built_collection: ^5.1.1
  from_css_color: ^2.0.0
  dropdown_search: 5.0.5
  flutter_animate: ^4.1.0
  json_path: ^0.4.2
  timeago: ^3.3.0
  page_transition: ^2.0.9
  auto_size_text: ^3.0.0
  percent_indicator: ^4.2.3
  mime_type: ^1.0.0
  easy_debounce: ^2.0.3
  image: ^3.1.3
  firebase_dynamic_links: ^5.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  snippet_coder_utils: ^1.0.9
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/